services:
  backend:
    image: barber-backend:latest
    deploy:
      replicas: 2
    volumes:
      - barber-db:/data
    networks:
      - barber_loadbalancing
    
  frontend:
    image: barber-frontend:latest
    ports:
      - 80:80
    networks:
      - barber_loadbalancing
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_HOST='%'
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=barber
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - barber_loadbalancing

networks:
  barber_loadbalancing:

volumes:
  barber-db:
    driver: local
    name: barber-db
  mysql-db:
    driver: local
    name: mysql-db
